env:
  node: true
  es6: true

rules:
  camelcase:
    - error
    - properties: never
      ignoreDestructuring: true
      allow: [child_process]
  no-unused-vars:
    - error
    - args: after-used
  prefer-arrow-callback: error
