#ifndef SRC_NODE_MOBILE_VERSION_H_
#define SRC_NODE_MOBILE_VERSION_H_

#include "node_version.h"

#define NODE_MOBILE_MAJOR_VERSION NODE_MAJOR_VERSION
#define NODE_MOBILE_MINOR_VERSION NODE_MINOR_VERSION
#define NODE_MOBILE_PATCH_VERSION NODE_PATCH_VERSION

#define NODE_MOBILE_PATCH_NUMBER 0

#define NODE_MOBILE_VERSION_IS_RELEASE NODE_VERSION_IS_RELEASE

# if NODE_MOBILE_VERSION_IS_RELEASE
#  define NODE_MOBILE_TAG "-patch." NODE_STRINGIFY(NODE_MOBILE_PATCH_NUMBER)
# else
#  define NODE_MOBILE_TAG "-patch." NODE_STRINGIFY(NODE_MOBILE_PATCH_NUMBER) "-pre"
# endif

#define NODE_MOBILE_VERSION_STRING  NODE_STRINGIFY(NODE_MOBILE_MAJOR_VERSION) "." \
                               NODE_STRINGIFY(NODE_MOBILE_MINOR_VERSION) "." \
                               NODE_STRINGIFY(NODE_MOBILE_PATCH_VERSION)     \
                               NODE_MOBILE_TAG

#endif  // SRC_NODE_MOBILE_VERSION_H_
