name: Test internet

on:
  workflow_dispatch:
  schedule:
    - cron: 5 0 * * *

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: [test/internet/**]
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths: [test/internet/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test-internet:
    if: github.repository == 'nodejs/node' || github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test Internet
        run: make test-internet -j2 V=1;
